on:
  pull_request:
  push:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  flake-check:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    name: Nix flake check
    runs-on: ${{matrix.os}}
    steps:
      - uses: wimpysworld/nothing-but-nix@main
        if: matrix.os == 'ubuntu-latest'
      - uses: cachix/install-nix-action@v31
      - uses: DeterminateSystems/magic-nix-cache-action@13
      - uses: actions/checkout@v5
      - run: nix flake metadata
      - run: nix flake check
