on:
  push:
    branches: [main]
  pull_request:
    types: [labeled, opened, synchronize, reopened, review_requested, ready_for_review]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  non-draft:
    runs-on: ubuntu-latest
    steps:
      - run: test "true" = "${{github.ref == 'refs/heads/main' || github.event.pull_request.draft == false}}"
  flake-check:
    needs: [non-draft]
    name: nix flake check
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v31
      - run: nix flake check -L github:vic/checkmate --override-input target github:$GITHUB_REPOSITORY/$GITHUB_SHA
  noflake:
    needs: [non-draft]
    name: noflake
    runs-on: ubuntu-latest
    steps:
      - uses: wimpysworld/nothing-but-nix@main
      - uses: cachix/install-nix-action@v31
      - uses: DeterminateSystems/magic-nix-cache-action@v13
      - uses: actions/checkout@v4
      - run: sed -i 's@# den.outPath@den.outPath@' templates/noflake/with-inputs.nix
      - run: |
          cat <<-EOF > templates/noflake/modules/ci-runtime.nix
          {
            _module.args.CI = true;
          }
          EOF
          git add templates/noflake/modules/ci-runtime.nix
      - run: cd templates/noflake && nix-build -A flake.nixosConfigurations.igloo.config.system.build.toplevel
  minimal:
    needs: [non-draft]
    name: minimal
    runs-on: ubuntu-latest
    steps:
      - uses: wimpysworld/nothing-but-nix@main
      - uses: cachix/install-nix-action@v31
      - uses: DeterminateSystems/magic-nix-cache-action@v13
      - uses: actions/checkout@v4
      - run: |
          cat <<-EOF > templates/minimal/modules/ci-runtime.nix
          {
            _module.args.CI = true;
          }
          EOF
          git add templates/minimal/modules/ci-runtime.nix
      - run: nix flake check -L ./templates/minimal --override-input den github:$GITHUB_REPOSITORY/$GITHUB_SHA
  bogus:
    needs: [non-draft]
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    name: Bogus ${{matrix.os}}
    runs-on: ${{matrix.os}}
    steps:
      - uses: wimpysworld/nothing-but-nix@main
      - uses: cachix/install-nix-action@v31
      - uses: DeterminateSystems/magic-nix-cache-action@v13
      - uses: actions/checkout@v4
      - run: |
          cat <<-EOF > templates/bogus/modules/ci-runtime.nix
          {
            _module.args.CI = true;
          }
          EOF
          git add templates/bogus/modules/ci-runtime.nix
      - run: nix flake check -L ./templates/bogus --override-input den github:$GITHUB_REPOSITORY/$GITHUB_SHA
  tests:
    needs: [non-draft]
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    name: Tests ${{matrix.os}}
    runs-on: ${{matrix.os}}
    steps:
      - uses: wimpysworld/nothing-but-nix@main
      - uses: cachix/install-nix-action@v31
      - uses: DeterminateSystems/magic-nix-cache-action@v13
      - run: nix flake init -t github:$GITHUB_REPOSITORY/$GITHUB_SHA#ci
      - run: sed -i "s@\"github:vic/den\"@\"github:vic/den/$GITHUB_SHA\"@" flake.nix
        if: matrix.os == 'ubuntu-latest'
      - run: sed -i '' "s@\"github:vic/den\"@\"github:vic/den/$GITHUB_SHA\"@" flake.nix
        if: matrix.os == 'macos-latest'
      - run: |
          cat <<-EOF > modules/ci-runtime.nix
          { lib, ... }:
          {
            _module.args.CI = true;
          }
          EOF
      - run: nix flake update den
      - run: nix flake metadata
      - run: nix flake check -L
  template:
    needs: [non-draft]
    strategy:
      # max-parallel: 1
      matrix:
        os: [ubuntu-latest, macos-latest]
        template: [default, example]
    name: Check template ${{matrix.template}} ${{matrix.os}}
    runs-on: ${{matrix.os}}
    steps:
      - uses: wimpysworld/nothing-but-nix@main
        if: matrix.os == 'ubuntu-latest'
      - uses: cachix/install-nix-action@v31
      # - uses: DeterminateSystems/magic-nix-cache-action@v13
      - run: nix flake init -t github:$GITHUB_REPOSITORY/$GITHUB_SHA#${{matrix.template}}
      - run: |
          cat <<-EOF > modules/ci-runtime.nix
          { lib, ... }:
          {
            flake-file.inputs.den.url = lib.mkForce "github:$GITHUB_REPOSITORY/$GITHUB_SHA";
            _module.args.CI = true;
          }
          EOF
      - run: nix run .#write-flake --override-input den "github:$GITHUB_REPOSITORY/$GITHUB_SHA"
      - run: nix flake update den
      - run: nix run .#write-flake
      - run: nix flake metadata
      - run: nix flake check -L --no-build
