on:
  pull_request:
  push:
    branches: [main]
jobs:
  flake-check:
    name: nix flake check
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v30
      - run: nix flake check -L github:vic/checkmate --override-input target github:$GITHUB_REPOSITORY/$GITHUB_SHA
  template:
    name: Check template
    runs-on: ubuntu-latest
    steps:
      - uses: wimpysworld/nothing-but-nix@main
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: |
          set -uveo pipefail
          mkdir templated; cd templated
          nix flake init -t github:$GITHUB_REPOSITORY/$GITHUB_SHA#default
          cat <<-EOF > modules/force.nix
          {
            flake-file.inputs.den.url = "github:$GITHUB_REPOSITORY/$GITHUB_SHA";
          }
          EOF
          nix run .#write-flake
          nix flake check
